#!/usr/bin/env bash
# PreToolUse guard — the floor under shared/generated-code-review.md.
#
# It exists because of an observed failure, in more than one skill: an agent
# opens a file whose banner says "Code generated by omnicore-gen. DO NOT EDIT.",
# reads that as a prohibition, and builds AROUND it — N queries folded in Go
# beside a generated fact, a second finder next to a generated one — while
# telling the developer "generated code cannot be changed". That sentence is
# false, and the workaround is worse than the edit it avoided.
#
# So this guard never refuses. Editing a generated file is legitimate and the
# generator ships `adopt` precisely for it. What the guard does is turn the edit
# into the CONVERSATION it should have been: ASK, so the developer — who pays
# the cost of a pinned file — is the one who says yes, and carry the two facts
# the agent keeps missing (it is allowed; it needs `adopt` afterwards).
#
# Silent (exit 0) for every file the generator does not own, for hook files
# (*_manual.go — already the author's, nothing to adopt), for the framework's
# own repository, for this plugin's own repository and its golden host, for a
# project that does not consume omnicore, and when jq is unavailable.
set -uo pipefail

command -v jq >/dev/null 2>&1 || exit 0

input=$(cat)
tool=$(printf '%s' "$input" | jq -r '.tool_name // empty')
file_path=$(printf '%s' "$input" | jq -r '.tool_input.file_path // .tool_input.filePath // .tool_input.path // empty')
[ -z "$file_path" ] && exit 0

case "$tool" in
  Write | Edit | MultiEdit) ;;
  *) exit 0 ;;
esac

# ------------------------------------------------------------ scope: the file
# Only a file that EXISTS and carries the owned banner. A Write creating a new
# file is not an edit of generated code, and a hook file (*_manual.go, whose
# banner says the opposite) is already the author's.
[ -f "$file_path" ] || exit 0
head -1 "$file_path" | grep -q 'Code generated by omnicore-gen\. DO NOT EDIT\.' || exit 0
# The checksum line is what makes it OWNED — it is the hash the next run
# compares. A file without one is not tracked and needs no adoption.
head -20 "$file_path" | grep -qE '^(//|--|#)[[:space:]]*checksum:' || exit 0

# ---------------------------------------------------------- scope: the project
dir=$(dirname "$file_path")
while [ ! -d "$dir" ] && [ "$dir" != "/" ] && [ -n "$dir" ]; do
  dir=$(dirname "$dir")
done
gomod=""
probe="$dir"
while [ -n "$probe" ] && [ "$probe" != "/" ]; do
  # This plugin's own repository — its testdata generates exactly these files,
  # and a guard that fires while the generator is being DEVELOPED is a guard
  # that gets disabled.
  [ -f "$probe/.claude-plugin/plugin.json" ] && exit 0
  [ -f "$probe/plugins/omnicore/.claude-plugin/plugin.json" ] && exit 0
  if [ -f "$probe/go.mod" ]; then gomod="$probe/go.mod"; break; fi
  probe=$(dirname "$probe")
done
[ -z "$gomod" ] && exit 0
# The framework itself, and the generator's vendored golden host.
grep -qE '^[[:space:]]*module[[:space:]]+github\.com/ClaudioSchirmer/omnicore[[:space:]]*$' "$gomod" && exit 0
grep -qE '^[[:space:]]*module[[:space:]]+github\.com/omnicore/gen-golden-host[[:space:]]*$' "$gomod" && exit 0
grep -q 'github\.com/ClaudioSchirmer/omnicore' "$gomod" || exit 0

# The path the developer will type, relative to the project root.
root=$(dirname "$gomod")
rel=${file_path#"$root"/}

# The message lives in a FUNCTION, the way guard-domain-membership.sh carries
# its routing table — not inline in a command substitution. That is not style:
# bash 3.2 (what macOS ships) mis-parses a quoted heredoc INSIDE $( ), and a
# single apostrophe in the prose then reads as an unterminated string and takes
# the whole guard down. A guard that dies on its own message is worse than no
# guard, so the heredoc is parsed once, at definition time.
message() {
  cat <<'MSG'
Editing generated code is ALLOWED — this is a question, not a refusal.

  file: @REL@

"// Code generated by omnicore-gen. DO NOT EDIT." is the Go convention that
makes linters skip a file. It is not a rule against changing it: the file is
ordinary Go in this repository, and the generator ships `adopt` precisely so a
hand edit survives regeneration. Never tell the developer that generated code
cannot be changed, and never build around it — N queries folded in Go, a
parallel finder, a wrapper that patches the answer. Each of those leaves two
answers to one question, and the worse one runs.

Two things this edit needs:

  1. THE DEVELOPER SAYS YES. They pay the cost, so they choose. Say what the
     generated code does, what the framework offers instead and why it is
     better, and what adopting costs: the file stops tracking the spec, so
     every later emitter improvement — a bug fixed, a guard closed — lands in
     every other project and never here. If the SPEC can express it, changing
     the spec and regenerating is cheaper and survives every upgrade; check
     `omnicore-gen explain keys` before assuming it cannot.

  2. ADOPT IT, in the same breath as the edit:

         omnicore-gen adopt @REL@ -why "<what the spec could not express>"

     Without it the next `generate` refuses the run rather than overwriting —
     your work is never lost, but the run stops for whoever meets it.

The full rule, with the workarounds it exists to stop:
shared/generated-code-review.md
MSG
}

msg=$(message)
msg=${msg//@REL@/$rel}

jq -n --arg r "$msg" \
  '{hookSpecificOutput:{hookEventName:"PreToolUse", permissionDecision:"ask", permissionDecisionReason:$r}}'
exit 0
